### ISSUE TITLE
Do I build the program???

### ISSUE THREAD

**Issue by T-T-7** [shockdude/fnf-to-sm#10]
I am very new to this and I want to do FNF charting but I have no idea on what to do

**Comment by shockdude** [comment]
You don't need to build it, there's pre-built releases here: https://github.com/shockdude/fnf-to-sm/releases
That being said, if you want to chart for FNF using Stepmania tools, I'd suggest Saturday Morning Steppin' instead: https://github.com/telperion/saturday-morning

**Comment by T-T-7** [comment]
oh thanks
