### ISSUE TITLE
Songs confirmed not to convert to StepMania

### ISSUE THREAD

**Issue by jack5github** [shockdude/fnf-to-sm#2]
I have testing the conversion from Friday Night Funkin' to StepMania, and the following tracks from Friday Night Funkin' fail to convert to StepMania files from the normal difficulty .json files supplied from FNF Version 5:
- Boopeedo
- Dadbattle
- Fresh
- Satin Panties
- South
- Spookeez
- Tutorial

**Comment by shockdude** [comment]
Oops I haven't checked this repo in a while. I'll try to work on this.

**Comment by shockdude** [comment]
This was already fixed in #1, but I'll upload a new exe release.
