### ISSUE TITLE
Any plans to upload this as a tool on GameBanana?

### ISSUE THREAD

**Issue by jack5github** [shockdude/fnf-to-sm#5]
GameBanana is currently the most visited location on the internet for Friday Night Funkin mods, ahead of YouTube. If you uploaded this project to GameBanana as a Tool, I think it would get a lot more recognition. https://gamebanana.com/games/8694

**Comment by shockdude** [comment]
No plans at the moment, but thanks for asking.
I'm working on fnf-to-sm for fun, I'm not really looking for recognition.
Also it's way too buggy haha. Patching it up to be actually usable will take a while.
